name: On Set Audio
favicon: null
layout_spectrum: 0.5374522930942476
typography_spectrum: 0.25604
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#eaeaea'
    - '#b9b9bb'
    - '#676a77'
    - '#2e394f'
  brandStrength: 0.25
  lightness: 0.0948817792814225
  saturation: 0.6864717034623027
  rhythmicContrast: 0.9432197690475732
purpose: []
