name: On Set Audio
favicon: null
layout_spectrum: 0.5374522930942476
typography_spectrum: 0.25435590418055654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.05591718154028058
  lightness: 0.0948817792814225
  saturation: 0.6864717034623027
  rhythmicContrast: 0.9432197690475732
purpose: []
